# Generated by Django 5.2.4 on 2025-07-07 15:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=32)),
                ('user_phone', models.PositiveIntegerField()),
                ('user_age', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(16), django.core.validators.MaxValueValidator(60)])),
                ('user_description', models.TextField()),
                ('user_city', models.CharField(max_length=32)),
                ('user_image', models.ImageField(upload_to='user_image/')),
            ],
        ),
    ]
